### ISSUE TITLE
[BUG] commitlint blocks committing on Windows

### ISSUE THREAD

**Issue by EmmaDawsonDev** [Learn-Build-Teach/deals-for-devs#207]
**Describe the bug**
The lint-commit command `"lint-commit": "npx --no-install commitlint --edit \"$1\"",` fails on Windows

**To Reproduce**
1. Make changes and run `git commit -m "fix: message`
2. Get error

**Expected behavior**

**Screenshots**
```
$ git commit -m "docs: make instructions clearer"

> deals-for-devs@0.1.0 lint-commit
> npx --no-install commitlint --edit $1

file:///C:/Users/squig/Documents/Dev%20projects/deals-for-devs/node_modules/@commitlint/cli/lib/cli.js:129
        throw err;
        ^

Error: ENOENT: no such file or directory, open 'C:\Users\squig\Documents\Dev projects\deals-for-devs\$1'
    at async open (node:internal/fs/promises:639:25)
    at async Object.readFile (node:internal/fs/promises:1249:14)
    at async getEditCommit (file:///C:/Users/squig/Documents/Dev%20projects/deals-for-devs/node_modules/@commitlint/read/lib/get-edit-commit.js:11:22)
    at async main (file:///C:/Users/squig/Documents/Dev%20projects/deals-for-devs/node_modules/@commitlint/cli/lib/cli.js:183:19) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\squig\\Documents\\Dev projects\\deals-for-devs\\$1'
}

Node.js v20.15.0
husky - commit-msg script failed (code 1)
```

**Desktop (please complete the following information):**
 - OS: Windows 11

**Suggested Solution**
Share you how you plan go about solving this bug. 

**Additional context**

**Comment by mibijoy007** [comment]
Hi,
I found a solution and it's working for me(win 10). Also tried on ubuntu and works.

Actually discussing it with @jamesqquick 

If he confirms I'll do a PR
